import { CustomHeadProps } from '@/common/types';
import Head from 'next/head'
/**
 * Добавляет метаданные к страницам.
 * P.S. История к ней не нужна, так как никакой визуальной
 * составляющей не владеет
 * @returns Component
 */
function CustomHead(props: CustomHeadProps) {

    const defaultTitle = "CloudSphere: Универсальный Интерфейс Облачных Вычислений"

    return (
        <Head>
            <title>{props.title ?? defaultTitle}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
}

export default CustomHead;