import SessionFormContainer from '@/auth/containers/SessionFormContainer'
import CustomPaper from '@/common/components/CustomPaper'
import { Container } from '@mui/material'
import Head from 'next/head'

export default function Home() {

  return (
    <>
      <Head>
        <title>CloudSphere: Универсальный Интерфейс Облачных Вычислений</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        maxWidth="lg"
        sx={{
          alignItems: 'center',
          display: 'flex',
          justifyContent: 'center',
          minHeight: '100vh',
        }}
      >
        <CustomPaper>
          <SessionFormContainer />
        </CustomPaper>
      </Container>
    </>
  )
}
